version: '3.2'
services:
  myservice:
    image: tsmean/express-typescript-example
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      labels:
        - "traefik.frontend.rule=Host:express-typescript-example.tsmean.com"
        - "traefik.port=6522"
        - "traefik.docker.network=traefik"
    ports:
      - "6522:6522"
    networks:
      - traefik

networks:
  traefik:
    external: true
